M48
; DRILL file {KiCad 7.0.5-0} date 2023 June 21, Wednesday 09:58:11
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-21T09:58:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X3.1Y-2.4
X3.1Y-2.5
X3.1Y-2.6
X3.1Y-2.7
X3.1Y-2.8
X3.7Y-2.4
X3.7Y-2.5
X3.7Y-2.6
X3.7Y-2.7
X3.7Y-2.8
T0
M30
