M48
; DRILL file {KiCad 7.0.5-0} date 2024 April 09, Tuesday 15:11:00
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-09T15:11:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.2520
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.4724
%
G90
G05
T1
X2.4803Y-3.937
X3.937Y-2.4803
X3.937Y-5.3937
X5.3937Y-3.937
T2
X3.937Y-3.937
T0
M30
